name: Release

on:
  workflow_dispatch:
    inputs:
      TAG:
        description: TAG (e.g., 1.0.0)
        required: true

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare
        id: prepare
        env:
          TAG: latest
        run: |
            echo ::set-output name=tag_name::latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Run GoReleaser
        run: |
            make release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_WRITE_PACKAGES }}
          VERSION: ${{ steps.prepare.outputs.tag_name }}
